---
- name: "List all roles within {{ project_root_folder }}/roles"
  ansible.builtin.find:
    paths: "{{ project_root_folder }}/roles"
    recurse: no
    file_type: directory
  register: upstream_roles

- ansible.builtin.include_tasks: roles/process_role.yml
  vars:
    role_folder: "{{ item }}"
  loop: "{{ upstream_roles.files }}"
  when:
    - (excluded_roles_from_downstream is defined and not (item.path | basename) in ( excluded_roles_from_downstream | join(',') ) ) or not excluded_roles_from_downstream is defined
