---
- name: "Ensure required parameters are provided"
  ansible.builtin.assert:
    that:
      - project_git_url is defined
      - project_root_folder is defined
    quiet: True
    fail_msg: "Missing required parameters"

- name: "Git clone {{ project_git_url }} [{{ project_git_version }}] into {{ project_root_folder }}]"
  ansible.builtin.git:
    repo: "{{ project_git_url }}"
    dest: "{{ project_root_folder }}"
    version: "{{ project_git_version | default(omit) }}"
  register: git_clone_res
  retries: 3
  delay: 15
  until: not git_clone_res.failed

- name: "Run git describe for galaxy.yml version override"
  ansible.builtin.command: git describe    # noqa command-instead-of-module
  args:
    chdir: "{{ project_root_folder }}"
  changed_when: false
  register: git_describe_result
  when: gitdescribe_galaxy_version is defined and gitdescribe_galaxy_version
  
- name: "Set git_describe_version"
  ansible.builtin.set_fact:
    git_describe_version: "{{ git_describe_result.stdout | default('') }}"
