---
- ansible.builtin.assert:
    that:
      - src is defined
      - dest is defined
    quiet: true
    fail_msg: 'Missing required parameters'

- name: "rsync {{ src }} to {{ dest }}"
  ansible.posix.synchronize:
    src: "{{ src }}"
    dest: "{{ dest }}"

- name: "Remove excluded roles from downstream"
  ansible.builtin.file:
    path: "{{ dest }}/{{ excluded_file }}"
    state: absent
  loop: "{{ excluded_roles_from_downstream }}"
  loop_control:
    loop_var: excluded_file
  when:
    - excluded_roles_from_downstream is defined and excluded_roles_from_downstream | length > 0
