---
- name: "Lookup molecule files"
  ansible.builtin.find:
    paths: "{{ molecule_dir }}"
    recurse: true
    patterns: '*.yml,*.j2'
  register: molecule_yaml

- name: "Include replace deps tasks"
  ansible.builtin.include_tasks: roles/replace_deps_to_upstream_name_to_downstream.yml
  vars:
    path_to_file: "{{ item.path }}"
  loop: "{{ molecule_yaml.files }}"

- name: "Include replace tasks"
  ansible.builtin.include_tasks: utils/replace_name_and_namespace.yml
  vars:
    path_to_file: "{{ item.path }}"
  loop: "{{ molecule_yaml.files }}"
