---
- name: "Ensure required parameters are provided"
  ansible.builtin.assert:
    that:
      - file_to_remove is defined
      - downstream_project is defined
    quiet: True
    fail_msg: "Missing required parameters."

# TODO: to be moved into the git role
- name: "Delete file"
  ansible.builtin.command: git rm -rf {{ file_to_remove }}    # noqa command-instead-of-module
  args:
    chdir: "{{ downstream_project }}"
