---
- name: "Check parameters"
  ansible.builtin.assert:
    that:
      - path_to_docs_folder is defined
      - upstream_namespace is defined
      - downstream_namespace is defined
    quiet: True
    fail_msg: "Missing required parameter."

- name: "Check directories"
  ansible.builtin.include_tasks: utils/check_dir_exists.yml
  vars:
    path_to_dir: "{{ path_to_docs_folder }}"

- name: "Lookup doc file candidates"
  ansible.builtin.find:
    paths: "{{ path_to_docs_folder }}"
    file_type: file
    recurse: true
    patterns: '*.yml,*.rst,*.md'
  register: docs

- name: "Include rename tasks"
  ansible.builtin.include_tasks: docs/rename_name_and_namespace.yml
  vars:
    path_to_file: "{{ item.path }}"
  loop: "{{ docs.files }}"

- name: "Lookup doc file candidates for placeholders"
  ansible.builtin.find:
    paths: "{{ path_to_docs_folder | dirname }}"
    recurse: true
    file_type: file
    patterns: '*.md'
    contains: "^<!--start.*"
  register: markdown

- name: "Include placeholder replacement tasks"
  ansible.builtin.include_tasks: docs/placeholders.yml
  vars:
    path_to_file: "{{ item.path }}"
  loop: "{{ markdown.files }}"
