---
- ansible.builtin.assert:
    that:
      - path_to_file is defined
      - upstream_namespace is defined
      - downstream_namespace is defined
    quiet: True
    fail_msg: "Missing required parameters."

- name: "Include rename vars in file (name)"
  ansible.builtin.include_tasks: utils/rename_vars_in_file.yml
  vars:
    upstream_value: "{{ upstream_name }}"
    downstream_value: "{{ downstream_name }}"

- name: "Include rename vars in file (namespace)"
  ansible.builtin.include_tasks: utils/rename_vars_in_file.yml
  vars:
    upstream_value: "{{ upstream_namespace }}"
    downstream_value: "{{ downstream_namespace }}"
