---
- ansible.builtin.import_playbook: ./fqcn_migration.yml
  vars:
    upstream_name: kubevirt
    downstream_name: kvirt
    upstream_collection_name: community
    downstream_collection_name: ansible
    project_git_url: 'https://github.com/ansible-collections/community.kubevirt.git'
    project_git_version: main
